# Site settings
title: Martin Goth
email: gothm@cs.uni-freiburg.de
description: "Computer Science student at Albert Ludwig University Freiburg."
baseurl: ""
url: "http://yourdomain.com"
username: gothma
twitter: magmaster

# Build settings
markdown: kramdown
permalink: pretty
