# Site settings
title: Martin Goth
email: gothm@ziisch.de
description: "Computer Science student at <br>[Albert-Ludwigs University Freiburg](http://www.informatik.uni-freiburg.de)."
baseurl: ""
url: "http://www.ziisch.de"
username: gothma
twitter: ziisch

# Build settings
markdown: kramdown
permalink: pretty
